apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: fedora
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"
        cat /etc/system-release  
        echo "-=-=-=-=-=-=-=-=-=-=-=-"
